version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  mongo:
    image: mongo

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstack_db